import {raw,withTransaction,type MutationResult} from './db/raw';
const env=process.env;
import {workdays,blockedReason,defaultBlocks,validDate,today} from '../src/lib/calendar';
type Row=Record<string,any>;
const uuid=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
function changed(r:MutationResult){if(!r.meta.changes)throw Error('Cette demande vient de changer. Actualisez le planning.');}
async function all(sql:string,args:unknown[]=[]){return (await raw().prepare(sql).bind(...args).all<Row>()).results;}
async function config(){const r=await all('SELECT * FROM settings');const s=Object.fromEntries(r.map(x=>[x.key,x.value]));return {firstWeek:s.firstWeek!=='false',blocksConfigured:s.blocksConfigured==='true'};}
async function periods(){return (await config()).blocksConfigured?await all('SELECT * FROM blocks ORDER BY start'):defaultBlocks;}
async function check(start:string,end:string,occupied=false){const days=workdays(start,end);if(start<today())throw Error('Choisissez une date à partir d’aujourd’hui.');const c=await config(),b=await periods();const bad=days.find(d=>blockedReason(d,b as any,c.firstWeek));if(bad)throw Error(`${bad} : ${blockedReason(bad,b as any,c.firstWeek)}. Choisissez une autre période.`);if(!occupied){const r=await all("SELECT days FROM requests WHERE status='approved'");if(r.some(x=>JSON.parse(x.days).some((d:string)=>days.includes(d))))throw Error('Une personne est déjà en congé sur cette période.');}return days;}
function fail(e:unknown){console.error('Planning',e);const m=e instanceof Error?e.message:'';return Response.json({error:/capacity/.test(m)?'Cette période est déjà occupée. Actualisez le planning.':/D1|SQLITE|database|binding|no such|constraint/i.test(m)?'Le planning est indisponible ou a changé. Actualisez et réessayez.':m||'Impossible d’enregistrer pour le moment.'},{status:400});}
export async function GET(req:Request){try{const u=new URL(req.url),admin=u.searchParams.get('admin')==='1',actor=u.searchParams.get('employee')||'';
const employees=await all('SELECT id,name,active FROM employees ORDER BY name');
const rows=await all('SELECT * FROM requests ORDER BY created DESC');
const requests=rows.map(r=>r.employee_id===actor||admin?r:{id:r.id,employee_id:r.employee_id,start:r.start,end:r.end,days:r.days,status:r.status,override:r.override,proposed_start:r.proposed_start,proposed_end:r.proposed_end,cancel_requested:r.cancel_requested});
return Response.json({employees,requests,blocks:await periods(),firstWeek:(await config()).firstWeek,profile:actor?await raw().prepare('SELECT * FROM employees WHERE id=?').bind(actor).first():null,outbox:admin?await all('SELECT * FROM outbox ORDER BY created DESC LIMIT 50'):[],mailReady:!!(env as any).RESEND_API_KEY&&!!(env as any).EMAIL_FROM},{headers:{'Cache-Control':'no-store'}});}catch(e){return fail(e);}}
async function queue(employee:string,body:string){const e=await raw().prepare('SELECT * FROM employees WHERE id=?').bind(employee).first<Row>();if(!e?.notify||!e.email)return;await raw().prepare('INSERT INTO outbox (id,employee_id,subject,body,status,created) VALUES (?,?,?,?,?,?)').bind(uuid(),employee,'Votre demande de congé',body,'queued',now()).run();}
async function send(){const c=env as any;if(!c.RESEND_API_KEY||!c.EMAIL_FROM)return 0;let sent=0;for(const o of await all("SELECT o.*,e.email,e.notify FROM outbox o JOIN employees e ON e.id=o.employee_id WHERE o.status='queued' LIMIT 20")){if(!o.notify)continue;const claim=await raw().prepare("UPDATE outbox SET status='sending' WHERE id=? AND status='queued'").bind(o.id).run();if(!claim.meta.changes)continue;try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+c.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':o.id},body:JSON.stringify({from:c.EMAIL_FROM,to:[o.email],subject:o.subject,text:o.body})});if(!r.ok)throw Error();await raw().prepare("UPDATE outbox SET status='sent' WHERE id=?").bind(o.id).run();sent++;}catch{await raw().prepare("UPDATE outbox SET status='queued' WHERE id=?").bind(o.id).run();}}return sent;}
async function mutate(req:Request){try{const p=await req.json() as Row,db=raw(),admin=p.admin===true,actor=String(p.employee||'');const requireAdmin=()=>{if(!admin)throw Error('Cette action est réservée à la gérante.');};
if(!admin){if(!actor)throw Error('Sélectionnez votre nom.');if(!await db.prepare('SELECT id FROM employees WHERE id=? AND active=1').bind(actor).first())throw Error('Ce salarié n’est pas actif.');}
if(p.action==='employee'){requireAdmin();const name=String(p.name||'').trim();if(!name||name.length>80)throw Error('Indiquez un nom de 1 à 80 caractères.');await db.prepare('INSERT INTO employees (id,name) VALUES (?,?)').bind(uuid(),name).run();}
else if(p.action==='archive'){requireAdmin();await db.prepare('UPDATE employees SET active=? WHERE id=?').bind(p.active?1:0,p.id).run();}
else if(p.action==='profile'){const email=String(p.email||'').trim();if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Vérifiez votre adresse e-mail.');if(p.notify&&!email)throw Error('Renseignez une adresse e-mail.');await db.prepare('UPDATE employees SET email=?,notify=? WHERE id=?').bind(email,p.notify?1:0,actor).run();}
else if(p.action==='request'){const employee=admin?String(p.target):actor;if(!await db.prepare('SELECT id FROM employees WHERE id=? AND active=1').bind(employee).first())throw Error('Sélectionnez un salarié actif.');const override=admin&&p.override===true,days=await check(p.start,p.end,override);const r=await db.prepare("INSERT INTO requests (id,employee_id,start,end,days,status,note,created,override) SELECT ?,?,?,?,?,'pending',?,?,? WHERE ?=1 OR NOT EXISTS (SELECT 1 FROM requests r,json_each(r.days) d WHERE r.status='approved' AND d.value IN (SELECT value FROM json_each(?)))").bind(uuid(),employee,p.start,p.end,JSON.stringify(days),String(p.note||'').slice(0,1500),now(),override?1:0,override?1:0,JSON.stringify(days)).run();if(!r.meta.changes)throw Error('Ces dates viennent d’être validées pour un autre salarié.');}
else if(['approve','refuse','propose','acceptProposal','declineProposal','cancel','confirmCancel'].includes(p.action)){const r=await db.prepare('SELECT * FROM requests WHERE id=?').bind(p.id).first<Row>();if(!r)throw Error('Demande introuvable.');if(!admin&&r.employee_id!==actor)throw Error('Cette demande appartient à un autre salarié.');let body='';
if(p.action==='approve'){requireAdmin();if(r.status!=='pending')throw Error('Cette demande a déjà été traitée.');await check(r.start,r.end,true);await db.prepare("UPDATE requests SET status='approved',override=?,answer=? WHERE id=? AND status='pending'").bind(p.override?1:0,String(p.answer||'').slice(0,1500),r.id).run().then(changed);body=`Vos congés du ${r.start} au ${r.end} sont validés.`;}
else if(p.action==='refuse'){requireAdmin();if(!['pending','proposed'].includes(r.status))throw Error('Cette demande a déjà été traitée.');await db.prepare("UPDATE requests SET status='refused',answer=?,proposed_start=NULL,proposed_end=NULL WHERE id=? AND status IN ('pending','proposed')").bind(String(p.answer||'').slice(0,1500),r.id).run().then(changed);body=`Votre demande du ${r.start} au ${r.end} est refusée. ${p.answer||''}`;}
else if(p.action==='propose'){requireAdmin();if(!['pending','proposed'].includes(r.status))throw Error('Cette demande a déjà été traitée.');await check(p.start,p.end);await db.prepare("UPDATE requests SET status='proposed',proposed_start=?,proposed_end=?,answer=? WHERE id=? AND status IN ('pending','proposed')").bind(p.start,p.end,String(p.answer||'').slice(0,1500),r.id).run().then(changed);body=`La gérante vous propose du ${p.start} au ${p.end}. Ouvrez l’application pour accepter ou décliner. ${p.answer||''}`;}
else if(p.action==='acceptProposal'){if(admin||r.status!=='proposed')throw Error('Le salarié doit accepter une proposition en cours.');const days=await check(r.proposed_start,r.proposed_end);await db.prepare("UPDATE requests SET start=proposed_start,end=proposed_end,days=?,status='approved',override=0,proposed_start=NULL,proposed_end=NULL WHERE id=? AND status='proposed'").bind(JSON.stringify(days),r.id).run().then(changed);body=`Les dates proposées, du ${r.proposed_start} au ${r.proposed_end}, sont acceptées et validées.`;}
else if(p.action==='declineProposal'){if(r.status!=='proposed')throw Error('Cette proposition n’est plus disponible.');await db.prepare("UPDATE requests SET status='pending',proposed_start=NULL,proposed_end=NULL,answer='Proposition déclinée par le salarié.' WHERE id=? AND status='proposed'").bind(r.id).run();}
else if(p.action==='cancel'){if(r.status==='approved')await db.prepare('UPDATE requests SET cancel_requested=1 WHERE id=?').bind(r.id).run();else if(['pending','proposed'].includes(r.status))await db.prepare("UPDATE requests SET status='cancelled' WHERE id=? AND status IN ('pending','proposed')").bind(r.id).run();else throw Error('Cette demande ne peut plus être annulée.');}
else{requireAdmin();if(!r.cancel_requested)throw Error('Aucune annulation demandée.');await db.prepare("UPDATE requests SET status='cancelled',cancel_requested=0 WHERE id=? AND cancel_requested=1").bind(r.id).run().then(changed);body=`L’annulation de vos congés du ${r.start} au ${r.end} est validée.`;}
if(body)await queue(r.employee_id,body);}
else if(p.action==='settings'){requireAdmin();if(!Array.isArray(p.blocks)||p.blocks.length>50)throw Error('Liste de périodes incorrecte.');const b=p.blocks.map((b:Row)=>{if(!validDate(b.start)||!validDate(b.end)||b.end<b.start||!String(b.label||'').trim())throw Error('Vérifiez les dates et le nom de chaque période.');return {...b,id:uuid(),label:String(b.label).slice(0,120)};});await db.batch([db.prepare('DELETE FROM blocks'),...b.map((b:Row)=>db.prepare('INSERT INTO blocks (id,label,start,end) VALUES (?,?,?,?)').bind(b.id,b.label,b.start,b.end)),db.prepare("INSERT INTO settings (key,value) VALUES ('blocksConfigured','true') ON CONFLICT(key) DO UPDATE SET value='true'"),db.prepare("INSERT INTO settings (key,value) VALUES ('firstWeek',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(p.firstWeek?'true':'false')]);}
else if(p.action==='sendMail'){requireAdmin();if(!(env as any).RESEND_API_KEY||!(env as any).EMAIL_FROM)throw Error('Le service d’envoi des e-mails n’est pas encore configuré.');}
else throw Error('Action inconnue.');let sent=0;try{sent=await send();}catch(e){console.error('Email queue',e);}return Response.json({ok:true,sent});}catch(e){return fail(e);}}

export async function POST(req:Request){try{return await withTransaction(()=>mutate(req));}catch(e){return fail(e);}}
